name: fixmobb
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  vector_math: ^2.1.2
  image_picker: ^0.8.7
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_core: ^3.6.0
  table_calendar: ^3.0.6
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  http: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/vectors/vector_120_x2.svg
  - assets/vectors/vector_128_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/union_1_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_82_x2.svg
  - assets/vectors/vector_103_x2.svg
  - assets/images/logo_bengkel_removebg_preview_1.png
  - assets/images/flatart_icons_removebg_preview_1.png
  - assets/vectors/line_10_x2.svg
  - assets/vectors/rectangle_991_x2.svg
  - assets/vectors/rectangle_994_x2.svg
  - assets/vectors/rectangle_993_x2.svg
  - assets/vectors/rectangle_99_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/images/untitled_design_171.png
  - assets/vectors/vector_159_x2.svg
  - assets/vectors/container_1_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/vector_24_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/images/fixmob.png
  - assets/images/start.png
  - assets/images/ban.png
  - assets/images/logofixmob.png
  - assets/images/onboard1.png
  - assets/images/onboard2.png
  - assets/images/onboard3.png
  - assets/images/sparepart.png
  - assets/images/ac.png
  - assets/images/tuneup.png
  - assets/images/rutin.png
  - assets/images/ban.png
  - assets/images/profil.png
  - assets/images/service.png
  - assets/images/oli_21.jpeg
  - assets/images/oli_7.jpeg
  - assets/images/oli_31.jpeg
  - assets/images/person_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/home_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/notifications_active_24_dp_000000_fill_0_wght_400_grad_0_opsz_242.png
  - assets/images/untitled_design_192.png
  - assets/images/shopping_cart_checkout_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/vectors/cil_chat_bubble_8_x2.svg
  - assets/vectors/line_6_x2.svg
  - assets/vectors/container_6_x2.svg
  - assets/vectors/vector_115_x2.svg
  - assets/vectors/vector_140_x2.svg
  - assets/vectors/vector_162_x2.svg
  - assets/images/oli_7.jpeg
  - assets/images/person_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/oli_21.jpeg
  - assets/images/shopping_cart_checkout_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/notifications_active_24_dp_000000_fill_0_wght_400_grad_0_opsz_242.png
  - assets/images/home_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/untitled_design_182.png
  - assets/images/oli_31.jpeg
  - assets/images/search_24_dp_ffffff_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/info_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/vectors/cil_chat_bubble_4_x2.svg
  - assets/vectors/star_57_x2.svg
  - assets/vectors/star_56_x2.svg
  - assets/vectors/star_54_x2.svg
  - assets/vectors/star_59_x2.svg
  - assets/vectors/star_52_x2.svg
  - assets/vectors/line_9_x2.svg
  - assets/vectors/star_55_x2.svg
  - assets/vectors/vector_158_x2.svg
  - assets/vectors/vector_113_x2.svg
  - assets/vectors/vector_129_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_136_x2.svg
  - assets/vectors/vector_64_x2.svg
  - assets/vectors/vector_168_x2.svg
  - assets/vectors/vector_161_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_157_x2.svg
  - assets/vectors/vector_153_x2.svg
  - assets/vectors/union_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/images/chevron_forward_24_dp_5_f_6368_fill_0_wght_400_grad_0_opsz_243.png
  - assets/images/riviera_rf_108_black_polish_dark_tint_1920212223_removebg_preview_1.png
  - assets/images/alarm_smart_wake_24_dp_5_f_6368_fill_0_wght_400_grad_0_opsz_241.png
  - assets/vectors/line_13_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/vector_117_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/rectangle_995_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/path_1_x2.svg
  - assets/vectors/path_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/container_2_x2.svg
  - assets/vectors/vector_124_x2.svg
  - assets/vectors/vector_33_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_106_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_147_x2.svg
  - assets/vectors/union_4_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/images/download_2_removebg_preview_1.png
  - assets/images/belajar_ukuran_derajat_pulser_pengapian_motor_studi_kasus_pengapian_honda_tiger_1.jpeg
  - assets/images/shopping_cart_checkout_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/home_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/untitled_design_192.png
  - assets/images/person_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/injector_nozzle_peugeot_rcz_1616_v_200_ps_injector_nozzle_removebg_preview_1.png
  - assets/images/notifications_active_24_dp_000000_fill_0_wght_400_grad_0_opsz_242.png
  - assets/vectors/cil_chat_bubble_x2.svg
  - assets/vectors/line_7_x2.svg
  - assets/vectors/vector_144_x2.svg
  - assets/vectors/vector_101_x2.svg
  - assets/vectors/union_3_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/images/notifications_active_24_dp_000000_fill_0_wght_400_grad_0_opsz_242.png
  - assets/images/shopping_cart_checkout_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/untitled_design_192.png
  - assets/images/foto_ban_bulat_mobil_bulat_ban_png_dan_vektor_dengan_background_transparan_untuk_unduh_gratis_removebg_preview_1.png
  - assets/images/justice_vs_injustice_he_did_by_pushing_the_tire_down_the_sidewalk_with_all_the_force_in_his_body_lee_49_chapter_4_removebg_preview_1.png
  - assets/images/person_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/home_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/vectors/cil_chat_bubble_5_x2.svg
  - assets/vectors/line_11_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/vector_119_x2.svg
  - assets/vectors/vector_30_x2.svg
  - assets/vectors/vector_141_x2.svg
  - assets/vectors/vector_133_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/vectors/vector_155_x2.svg
  - assets/images/untitled_design_161.png
  - assets/images/logo_1.png
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_107_x2.svg
  - assets/vectors/vector_46_x2.svg
  - assets/vectors/vector_118_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/vector_142_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/vector_132_x2.svg
  - assets/vectors/union_2_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/images/logo_1.png
  - assets/images/gps_11.png
  - assets/images/download_1_removebg_preview_1.png
  - assets/images/any_car_problems_the_tyre_factory_can_assist_with_any_of_your_car_needs_2.jpeg
  - assets/images/maps_1.jpeg
  - assets/vectors/star_31_x2.svg
  - assets/vectors/star_63_x2.svg
  - assets/vectors/star_12_x2.svg
  - assets/vectors/star_41_x2.svg
  - assets/vectors/star_33_x2.svg
  - assets/vectors/star_5_x2.svg
  - assets/vectors/star_32_x2.svg
  - assets/vectors/star_3_x2.svg
  - assets/vectors/star_510_x2.svg
  - assets/vectors/cil_chat_bubble_11_x2.svg
  - assets/vectors/star_1_x2.svg
  - assets/vectors/star_42_x2.svg
  - assets/vectors/star_13_x2.svg
  - assets/vectors/star_6_x2.svg
  - assets/vectors/star_43_x2.svg
  - assets/vectors/star_58_x2.svg
  - assets/vectors/star_61_x2.svg
  - assets/vectors/star_62_x2.svg
  - assets/vectors/star_11_x2.svg
  - assets/vectors/star_4_x2.svg
  - assets/vectors/star_51_x2.svg
  - assets/images/person_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/home_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/shopping_cart_checkout_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/check.png
  - assets/images/right.png
  - assets/images/notifications_active_24_dp_000000_fill_0_wght_400_grad_0_opsz_242.png
  - assets/images/untitled_design_201.png
  - assets/vectors/cil_chat_bubble_12_x2.svg
  - assets/vectors/line_x2.svg
  - assets/vectors/type_regular_state_outline_library_calling_x2.svg
  - assets/vectors/stroke_12_x2.svg
  - assets/vectors/more_circle_x2.svg
  - assets/vectors/bag_x2.svg
  - assets/vectors/stroke_13_x2.svg
  - assets/vectors/search_x2.svg
  - assets/vectors/group_10_x2.svg
  - assets/vectors/home_x2.svg
  - assets/vectors/discount_x2.svg
  - assets/vectors/heart_x2.svg
  - assets/vectors/stroke_11_x2.svg
  - assets/vectors/notification_x2.svg
  - assets/vectors/star_x2.svg
  - assets/vectors/stroke_1_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/images/vector.jpeg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/cil_chat_bubble_6_x2.svg
  - assets/images/untitled_design_171.png
  - assets/vectors/ellipse_9_x2.svg
  - assets/vectors/ellipse_8_x2.svg
  - assets/vectors/ellipse_10_x2.svg
  - assets/vectors/vector_156_x2.svg
  - assets/images/logo.png
  - assets/images/icon.png
  - assets/vectors/ellipse_81_x2.svg
  - assets/vectors/ellipse_102_x2.svg
  - assets/vectors/ellipse_91_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/vector_127_x2.svg
  - assets/images/untitled_design_121.png
  - assets/vectors/ellipse_82_x2.svg
  - assets/vectors/ellipse_92_x2.svg
  - assets/vectors/ellipse_103_x2.svg
  - assets/vectors/vector_152_x2.svg
  - assets/vectors/container_3_x2.svg
  - assets/vectors/vector_150_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_110_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/vectors/container_4_x2.svg
  - assets/vectors/vector_146_x2.svg
  - assets/vectors/union_5_x2.svg
  - assets/vectors/container_8_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/vector_22_x2.svg
  - assets/vectors/vector_130_x2.svg
  - assets/vectors/vector_114_x2.svg
  - assets/vectors/vector_108_x2.svg
  - assets/vectors/container_base_x2.svg
  - assets/vectors/icon_meetings_fill_x2.svg
  - assets/vectors/subtract_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/container_x2.svg
  - assets/vectors/vector_131_x2.svg
  - assets/vectors/vector_61_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/rectangle_992_x2.svg
  - assets/images/screenshot_20240811021319_removebg_preview_1.png
  - assets/images/notifications_active_24_dp_000000_fill_0_wght_400_grad_0_opsz_242.png
  - assets/images/person_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/home_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/untitled_design_192.png
  - assets/images/shopping_cart_checkout_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/vectors/line_2_x2.svg
  - assets/vectors/cil_chat_bubble_3_x2.svg
  - assets/images/the_benefits_of_scalable_mapping_tools_google_maps_platform_1.jpeg
  - assets/images/rectangle_105.png
  - assets/images/arrow_split_24_dp_5_f_6368_fill_0_wght_400_grad_0_opsz_241.png
  - assets/vectors/arrow_3_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_122_x2.svg
  - assets/vectors/vector_149_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/notion_logo_x2.svg
  - assets/vectors/vector_138_x2.svg
  - assets/images/untitled_design_101.png
  - assets/vectors/ellipse_83_x2.svg
  - assets/vectors/ellipse_101_x2.svg
  - assets/vectors/ellipse_93_x2.svg
  - assets/images/notifications_active_24_dp_000000_fill_0_wght_400_grad_0_opsz_242.png
  - assets/images/untitled_design_192.png
  - assets/images/temu_1_pc_air_conditioner_pressure_gauge_with_fluorine_compatible_with_r_32_r_410_ar_22_r_134_arefrigerants_ideal_for_heat_cooling_systems_and_air_purifiers_removebg_preview_1.png
  - assets/images/shopping_cart_checkout_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/jual_jerigen_besi_bensin_solar_army_nato_military_steel_jerrycan_tanki_bahan_bakar_20_liter_removebg_preview_1.png
  - assets/images/battery_charge_clipart_hd_png_battery_charge_indicator_icon_battery_icons_indicator_icons_battery_icon_png_image_for_free_download_removebg_preview_1.png
  - assets/images/person_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/untitled_design_182.png
  - assets/images/home_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/vectors/cil_chat_bubble_7_x2.svg
  - assets/vectors/line_5_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/group_4_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/container_5_x2.svg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/union_6_x2.svg
  - assets/images/notifications_active_24_dp_000000_fill_0_wght_400_grad_0_opsz_242.png
  - assets/images/home_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/trophy_24_dp_8_c_1_a_10_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/person_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/oli_31.jpeg
  - assets/images/right.png
  - assets/images/shopping_cart_checkout_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/vectors/star_53_x2.svg
  - assets/vectors/line_4_x2.svg
  - assets/vectors/cil_chat_bubble_2_x2.svg
  - assets/vectors/vector_164_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/vector_32_x2.svg
  - assets/vectors/vector_109_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/vector_135_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/images/chat_add_on_24_dp_ffffff_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/ellipse_47.jpeg
  - assets/vectors/line_1_x2.svg
  - assets/vectors/ellipse_46_x2.svg
  - assets/vectors/ellipse_471_x2.svg
  - assets/vectors/ellipse_48_x2.svg
  - assets/images/untitled_design_161.png
  - assets/images/logo_1.png
  - assets/vectors/vector_105_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/images/riviera_rf_108_black_polish_dark_tint_1920212223_removebg_preview_1.png
  - assets/images/calendar_month_24_dp_5_f_6368_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/chevron_forward_24_dp_5_f_6368_fill_0_wght_400_grad_0_opsz_243.png
  - assets/vectors/line_8_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/vector_163_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_137_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/vector_148_x2.svg
  - assets/vectors/vector_125_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_134_x2.svg
  - assets/images/bagian_bagian_mesin_otomotif_suku_cadang_mesin_otomotif_suku_cadang_suku_cadang_mobil_png_transparan_clipart_dan_file_psd_untuk_unduh_gratis_removebg_preview_1.png
  - assets/images/cold_temperature_vector_hd_png_images_gear_hot_and_cold_round_sign_logo_temperature_balance_icon_sun_gear_icons_logo_icons_sun_icons_png_image_for_free_download_removebg_preview_1.png
  - assets/images/shopping_cart_checkout_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/person_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/images/vector_car_parts_with_garage_removebg_preview_1.png
  - assets/images/vector_brake_disk_with_small_spares_removebg_preview_1.png
  - assets/images/mobil_removebg_preview_1.png
  - assets/images/any_car_problems_the_tyre_factory_can_assist_with_any_of_your_car_needs_2.jpeg
  - assets/images/notifications_active_24_dp_000000_fill_0_wght_400_grad_0_opsz_242.png
  - assets/images/home_24_dp_000000_fill_0_wght_400_grad_0_opsz_241.png
  - assets/vectors/line_3_x2.svg
  - assets/vectors/cil_chat_bubble_9_x2.svg
  - assets/vectors/cil_chat_bubble_10_x2.svg
  - assets/vectors/vector_160_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_145_x2.svg
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/container_7_x2.svg
  - assets/vectors/vector_167_x2.svg
  - assets/images/image_17.png
  - assets/images/image_13.png
  - assets/images/image_12.png
  - assets/images/image_10.png
  - assets/images/image_14.png
  - assets/images/image_11.png
  - assets/images/image_16.png
  - assets/images/image_15.png
  - assets/images/premium_photo_oil_fuel_or_air_filter_for_engine_car_isolated_on_white_background_removebg_preview_1.png
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/vector_151_x2.svg
  - assets/vectors/vector_112_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/images/logo_1.png
  - assets/images/pict.png
  - assets/images/logo_1.png
  - assets/images/untitled_design_161.png
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/vector_139_x2.svg
  - assets/vectors/union_7_x2.svg
  - assets/vectors/vector_126_x2.svg
  - assets/vectors/cil_chat_bubble_1_x2.svg
  - assets/vectors/line_12_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/subtract_2_x2.svg
  - assets/vectors/vector_143_x2.svg
  - assets/vectors/vector_166_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_165_x2.svg
  - assets/vectors/vector_123_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_31_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/vector_111_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/subtract_1_x2.svg
  - assets/vectors/vector_121_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/vector_79_x2.svg